### ISSUE TITLE
[shell]: Unknown command: pass2csv

### ISSUE THREAD

**Issue by ThoriumTextile** [reinefjord/pass2csv#13]
Now i think i might be just too stupid for a simple program like this, but whenever i run it after installation it says that, well, it's not installed.
I did use the new README, and even tried the old one but to no avail.
The shell syntax highlighting (fish in my case) turns red, suggesting that somehow pass2csv isn't installed.

I'm pretty sure i'm just missing something, am i?

**Comment by reinefjord** [comment]
Did you install it with `python3 -m pip install --user pass2csv`? Pip puts the executables in `~/.local/bin` (at least on Linux), so you have to make sure that you have that directory on your `$PATH`. In bash, you would have `export PATH="$HOME/.local/bin:$PATH"` in `.bashrc` or `.profile`, I'm not sure how you export variables in fish.

**Comment by ThoriumTextile** [comment]
Oh tysm!
I'm more of a power user (aka break shit an then fumble for hours until you fix it). Aside that, i had no idea $PATH had a role. The weird thing is that it didn't work on bash either. Anyway i just ` 
set PATH "$HOME/.local/bin/:$PATH" ` and it worked!
Thanks again, friend!

-----------------------
https://tutanota.com



15 dic 2020, 18:27 da 3ffd1d4d-eb10-463a-b1dc-51becd540e37@anonaddy.me:

**Comment by reinefjord** [comment]
The `$PATH` variable is a list of all places your shell should look for executables, if you do `echo $PATH` you'll see that `/bin` and `/usr/bin` are there. What you're doing with `set PATH "~/.local/bin/:$PATH` is saying that the new `$PATH` is `~/.local/bin/ + <the previous $PATH>`, that is, adding the directory to the front of the variable.

Happy to help!

**Comment by xxxcrow** [comment]
@ThoriumTextile also it's possible just to do export without bashrc
And also just: python3 ~/.local/bin/pass2csv
