### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by Nikifoi4** [reinefjord/pass2csv#14]
Program get crashed when password use russian symbols
```
Traceback (most recent call last):
  File "/home/nikifoi4/pass2csv/./pass2csv", line 277, in <module>
    main(**kwargs)
  File "/home/nikifoi4/pass2csv/./pass2csv", line 110, in main
    set_data(entry, str(decrypted), exclude, get_fields, get_lines)
  File "/usr/lib/python3.9/site-packages/gnupg.py", line 610, in _as_text
    return self.data.decode(self.gpg.encoding, self.gpg.decode_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 34: invalid continuation byte
```

**Comment by reinefjord** [comment]
You can choose which encoding to use with `--encoding <your encoding>`, which is passed to python-gnupg. You should be able to choose from any of the [standard encodings](https://docs.python.org/3.7/library/codecs.html#standard-encodings) in Python. I'm not sure which one is most commonly used for Russian, maybe try `--encoding iso8859_5`?

If you have files with different encodings it will still crash however, which is not good, and it shouldn't crash in the first place but rather just skip the file, so I consider this a bug.

**Comment by reinefjord** [comment]
I've just uploaded v0.3.0 to PyPI which does not crash on failed decode. It also changes `--encoding` to `--encodings` which allows multiple comma-separated encodings.
