### ISSUE TITLE
[Question] Where to import/export?

### ISSUE THREAD

**Issue by xxxcrow** [reinefjord/pass2csv#15]
Hi, I'm trying to move to bitwarden
I've read somebody's experience of doing this by importing the CSV in keepass
But my keepass shows no passwords
And also worth mentioning that my pass files are a bit different, I don't have URL

**Comment by reinefjord** [comment]
I actually just a few days ago saw a project that converts pass2csv output to whatever Bitwarden wants: https://github.com/sklukin/pass2bitwarden, mind trying that?

**Comment by xxxcrow** [comment]
@reinefjord I found it too 😃
But the script is not working, I created an issue to ask 😄
The repo was initiated 2 days ago

**Comment by xxxcrow** [comment]
@reinefjord but anyway, why does keepass show no passwords after import? 
What is example command for?

**Comment by reinefjord** [comment]
Sorry about no response. I would need more info on how you are running pass2csv to figure this out. Is this issue still relevant?
