### ISSUE TITLE
Too dirty to make a pull request with it

### ISSUE THREAD

**Issue by Trollwut** [reinefjord/pass2csv#2]
Hi mate!

I made some quick and dirty changes to your code, as I haven't got a standardized format in my `pass`-files. I imported from two different password managers and exporting it resulted in a mess. (e.g. imported from LastPass, but created new passwords with QtPass/pass)

Maybe someone needs that code, too.

It's here in this pastebin: https://pastebin.com/pELhX9Wf

I guess it would be a better approach for me to read every line and look for keywords like "login" and "username" to then apply this input to a variable.
My approach here was just simply shuffling around til it was good, so... it's not a nice code for a pull request, but some may consider it helpful anyway. :)

**Comment by reinefjord** [comment]
Hi! I would suggest forking this repo and adding your changes as a commit, you could then also edit the README to explain your changes. Very nice of you to share it though!
