### ISSUE TITLE
Windows line feeds created on Linux

### ISSUE THREAD

**Issue by MaxG87** [reinefjord/pass2csv#26]
Thank you for this fantastic tool! I think it will save me quite some headaches!

I am on Debian 12. I got my version from PyPI. Unfortunately, there is no `--version` flag, but according to `pipx` I am using version 1.0.0.

When I ran an export of my database, seemingly everything succeeded and an output file was created. I haven't checked in detail yet, though. However, I was irritated because at the end of the line I saw `^M` symbols. When I opened the CSV using a HEX editor, it showed that there are `0d0a` bytes, which indicates that line breaks are `\r\n`.

The first two lines of the hexdump follow:

```
00000000  47 72 6f 75 70 28 2f 29  2c 54 69 74 6c 65 2c 50  |Group(/),Title,P|
00000010  61 73 73 77 6f 72 64 2c  4e 6f 74 65 73 0d 0a 43  |assword,Notes..C|
```

I would highly appreciate if line breaks could be created OS aware.

Thank you very much!

**Comment by reinefjord** [comment]
Thank you for the bug report! I'll call that a bug, I'd be surprised if anyone were using pass or this tool on Windows. I've pushed a new version to PyPI that uses unix linebreaks :)
