### ISSUE TITLE
Have a setup.py entry point for more reliable pipx installations

### ISSUE THREAD

**Issue by Gitznik** [reinefjord/pass2csv#27]
Hey there,

currently this tool cannot be invoked via pipx, if pipx bases its virtual environments in a path that contains spaces, which is the default on mac, as per the mac documentation. This is the case since pipx 1.3.

The solution is to provde a entry point, see the [pipx docs](https://pipx.pypa.io/stable/how-pipx-works/#developing-for-pipx).

As you recommend installing this tool via pipx, it would be great if you could update your package accordingly.

Thanks!

based on https://github.com/pypa/pipx/issues/1212

**Comment by chrysle** [comment]
I guess this would practically mean adding the following to your `setup.cfg` (see the [`setuptools` documentation](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html)):

```ini
[options.entry_points]
console_scripts =
    executable-name = pass2csv:main
``` 
I'm a notorious `pass` user, too, by the way, so thanks for developing this tool!

**Comment by reinefjord** [comment]
I've refactored how pass2csv does packaging including setting an entry point in https://github.com/reinefjord/pass2csv/commit/44d82c5a54de8415b88acfd60c844bbfa868c7e5 and pushed a new version to pypi. Installation into paths with spaces now seems to work, at least on Linux:
```
$ which pass2csv | xargs readlink
/home/spaces are fun!/.local/share/pipx/venvs/pass2csv/bin/pass2csv
$ pass2csv --version
pass2csv 1.1.1
```

Thank you for the heads-up and thanks for pipx!

**Comment by Gitznik** [comment]
Thanks for resolving so rapidly!
