### ISSUE TITLE
README has wrong installation instructions

### ISSUE THREAD

**Issue by verajosemanuel** [reinefjord/pass2csv#8]
installed, but unable to execute.
` 
python3 -m pip install --user python-gnupg

Collecting python-gnupg

  Downloading python_gnupg-0.4.6-py2.py3-none-any.whl (17 kB)

Installing collected packages: python-gnupg

Successfully installed python-gnupg-0.4.6

 ❯  python3 pass2csv.py ~/.password-store

python3: can't open file 'pass2csv.py': [Errno 2] No such file or directory

 ✘ ❯ pass2csv --help

 command not found: pass2csv
`

**Comment by reinefjord** [comment]
Sorry, the README is outdated. You can install pass2csv with
```
python3 -m pip install --user pass2csv
```
I'll update the README with correct instructions.

**Comment by verajosemanuel** [comment]
I have no issue on installing but on executing.

**Comment by reinefjord** [comment]
Run it without `python3` and `.py`, just `pass2csv`.

**Comment by keithkaikai** [comment]
I get the `zsh: command not found: pass2csv` error

**Comment by reinefjord** [comment]
Is the pip installation folder on your path? See https://github.com/reinefjord/pass2csv/issues/13#issuecomment-745442589
