### ISSUE TITLE
Minimum Python version

### ISSUE THREAD

**Issue by winny-** [reinefjord/pass2csv#9]
Hello, while looking into using this tool. I ran into the following error, and after some head scratching, I realized I need Python 3.8 or later to use this package.

```
(venv) winston@snowcrash ~/projects/pass2csv $ ./pass2csv 
Traceback (most recent call last):
  File "./pass2csv", line 185, in <module>
    PARSER = OptionsParser()
  File "./pass2csv", line 166, in __init__
    help="strings to interpret as names of login fields (only used with -x)"
  File "/usr/lib/python3.7/argparse.py", line 1358, in add_argument
    raise ValueError('unknown action "%s"' % (action_class,))
ValueError: unknown action "extend"
```

To eliminate the possibility of this happening to other users, I humbly suggest adding classifiers for Python Versions to `setup.py`. [Here's a list of classifiers](https://pypi.org/classifiers/). It might also be nice to have this compatibility information in the README as well.

Thanks for pass2csv, have a good one :).

**Comment by reinefjord** [comment]
I've replaced the 3.8-dependent code with corresponding custom code in 5e457d8da6161398828bbaf5f7af5d4f769bf778 and pushed a new release to PyPI. `python-gnupg` expects Python 3.6, so I've tested with that and set it as the minimum required Python version.

Thank you for the heads-up!
